apiVersion: v1
kind: Service
metadata:
  name: gitea-outbound-service
  namespace: jenkins
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: gitea
  type: NodePort  
  ports:
    - name: gitea-app
      port: 3000
      targetPort: 3000
      nodePort: 30300
