apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec: 
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    path: jenkins-chart/
    repoURL: https://github.com/loydpadgett/jenkins-chart.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
