---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenkins
spec:
  roles:
    - name: read-sync
      description: read and sync privileges.
      policies:
        - p, proj:jenkins:read-sync, applications, get, jenkins/*, allow
        - p, proj:jenkins:read-sync, applications, sync, jenkins/*, allow
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Project to configure my own personalized jenkins installation with Argocd
  destinations:
    - namespace: jenkins
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/loydpadgett/jenkins-chart.git