apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
        {{ .Values.podSecurityContext.fsGroup }}
        {{ .Values.securityContext.runAsUser indent 8 }}
      serviceAccountName: {{ .Values.securityAccountName }}
      containers:
        - name: jenkins
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- with .Values.resources }}
          resources:
            limits:
              memory: {{ .limits.memory }}
              cpu: {{ .limits.cpu }}
            requests:
              memory: {{ .requests.memory }}
              cpu: {{ .requests.cpu }}
          {{- end }}
          ports:
            {{- with .Values.service.http }}
            - name: {{ .name }} 
              containerPort: {{ .port }}
            {{- end }}

            {{- with .Values.service.jnlp }}
            - name: {{ .name }}
              containerPort: {{ .port }} 
            {{- end }}
          {{- with .Values.livenessProbe.httpGet }}
          livenessProbe:
            httpGet:
              path: {{ .path }} 
              port: {{ .port }} 
          {{- end }}
          {{- with .Values.livenessProbe }}
            initialDelaySeconds: {{ .initialDelaySeconds }} 
            periodSeconds: {{ .periodSeconds }} 
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}  
          {{- end }}

          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home         
      volumes:
      - name: jenkins-data
        hostPath:
          path: /Users/loyd.padgett/git/jenkins/jenkins-app/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
