apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: gitea-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: git-pvc
    namespace: jenkins
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  local: 
    path: /Users/loyd.padgett/git/jenkins/gitea-app/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In 
          values:
          - 192.168.65.4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-avatar
spec:
  storageClassName: local-storage
  claimRef:
    name: gitea-avatar
    namespace: jenkins
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /Users/loyd.padgett/git/jenkins/gitea-app/config/me.jpg
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In 
          values:
          - 192.168.65.4
